baseURL = 'https://cool-gelato-7d2273.netlify.app/'
languageCode = 'en-us'
title = 'My New Hugo Site'
[params]
    dateFormat = "02 Jan 2006"

#################### default parameters ################################
[languages]
  [languages.en]
    languageName = "English"
    flag = "en_gb.gif"
    weight = 1

  [languages.en.params]
    footer_subtitle = "One single AI-powered web app for all your customer care."
    footer_title = "A BETTER WAY TO ENGAGE AND RETAIN YOUR CUSTOMERS." 
    footer_copy = "© 2003-2020 Clienk-All Rights Reserved"
    footer_address = "President Mansion <br> Huashan Road 868, Building D, <br> Level 0, Office B <br>Shanghai, China"
    btn = "Request A Demo"
    btn_link = "/request-a-demo"

  [languages.zh]
    languageName = "曼陀林"
    flag = "zh_cn.gif"
    weight = 2

  [languages.zh.params]
    footer_subtitle = "独立的人工智能应用，为您提供所有的客户服务"
    footer_title = "一个更好的方式去吸引和留住客户"
    footer_copy = "© 2003-2020 Clienk-保留所有权限"
    footer_address = "上海市长宁区华山路868弄6号总统公寓D座B0室"
    btn = "寻求演示"
    btn_link = "/zh/request-a-demo"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
